name: fennec_socket_io_server
description: this plugin belongs to Fennec Framework. it can be used to implement a performant realtime connection from server side.
version: 0.0.3
homepage: https://github.com/Fennec-Framework/fennec_socket_io_server
issue_tracker: https://github.com/Fennec-Framework/fennec_socket_io_server/issues

environment:
  sdk: ">=2.16.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  fennec: ^1.0.4
  lints: ^1.0.0
dependencies:
  uuid: ^3.0.6
