name: fennec_socket_io_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies:
  fennec: ^1.0.4
  js: ^0.6.4
  uuid: ^3.0.6
